---
title: "shintyoku"
output: 
  html_document: 
    keep_md: yes
---
```{r, message=FALSE}
# Library読み込み
library(ggplot2)
library(plyr)
library(dplyr)
library(stringr)
library(magrittr)
library(grid)
library(yeah)
library(scales)
library(lubridate)
```

```{r}
#フォントサイズ・パラメーター
FS_plot.mg = unit(c(1,1,1,1), "cm") #グラフの位置マージン（"grid"が必要）
FS_lab.x.mg = -2.0 # X軸ラベルのマージン
FS_lab.y.mg = 2.5 #Y軸ラベルのマージン
FS_lab = 20   #ラベル
FS_axis = 20   #軸（目盛）
```

```{r}
# 本日の進捗(macでしか動かず)
shinchoku_test <- function (goal, num = 1) {
  commit <- system("git log --since='$(date +'%Y-%m-%d') 00:00:00' --no-merges --oneline | wc -l", 
              intern = T) %>%
    stringr::str_trim() %<>% as.numeric()

  yeah::doudesuka(num = num)
  Sys.sleep(2.0)
  print(paste("今日のコミット数は ", commit, 
              ifelse(commit < goal, 
               c(" 進捗だめです orz"), c(" 進捗あります!!"))))
}
```
参考：[進捗を評価する関数を作った #進捗を支える技術](http://qiita.com/uri/items/d470ba8d68bf9dabebd3)

```{r}
# 進捗データの読み込み
data <- read.csv("commit_ref.csv", header = F, col.names = c("Date","Commit_name"))
data$Date <- parse_date_time(data$Date,"%y/%m/%d")

df <- data %>% group_by(Date) %>% summarise(cnt = n())
df <- df %>% mutate(cnt_sum = cumsum(df$cnt))
```

```{r, fig.align='center'}
# 進捗の可視化
gp = ggplot(df, aes(x=Date)) + theme_bw()
gp = gp + geom_bar(aes(y=cnt), stat = "identity", fill="#00BF7D")
gp = gp + geom_point(aes(y=cnt_sum), col="#D89000", size=4)
gp = gp + geom_line(aes(y=cnt_sum), col="#D89000", size=1)
gp = gp + scale_x_datetime(labels = date_format("%m/%d"))

#ラベル・軸のフォントサイズ、空白を調節
gp = gp + xlab("Date") + ylab("number of commits")
gp = gp + theme(axis.title.x=element_text(size=FS_lab, vjust=FS_lab.x.mg, face="bold"),
                  axis.title.y=element_text(size=FS_lab, vjust=FS_lab.y.mg, face="bold"),
                  axis.text=element_text(size=FS_axis))

# 全体的な空白の調整（端からグラフがどれだけ離れているか）
gp = gp + theme(plot.margin = FS_plot.mg) 
print(gp)
```

```{r}
# 1日の終わりに
shinchoku_test(2)
```
