# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AgeInDays.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AgeInDays(object):
    def setupUi(self, AgeInDays):
        AgeInDays.setObjectName("AgeInDays")
        AgeInDays.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        AgeInDays.setFont(font)
        self.centralwidget = QtWidgets.QWidget(AgeInDays)
        self.centralwidget.setObjectName("centralwidget")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(220, 400, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.input_target1_days = QtWidgets.QLineEdit(self.centralwidget)
        self.input_target1_days.setGeometry(QtCore.QRect(290, 370, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_target1_days.setFont(font)
        self.input_target1_days.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_target1_days.setObjectName("input_target1_days")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(450, 10, 321, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setObjectName("calendarWidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 160, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.input_target2_days = QtWidgets.QLineEdit(self.centralwidget)
        self.input_target2_days.setGeometry(QtCore.QRect(290, 430, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_target2_days.setFont(font)
        self.input_target2_days.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_target2_days.setObjectName("input_target2_days")
        self.input_birthday = QtWidgets.QDateEdit(self.centralwidget)
        self.input_birthday.setGeometry(QtCore.QRect(120, 260, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_birthday.setFont(font)
        self.input_birthday.setObjectName("input_birthday")
        self.switch_birthday = QtWidgets.QRadioButton(self.centralwidget)
        self.switch_birthday.setGeometry(QtCore.QRect(280, 260, 141, 31))
        self.switch_birthday.setObjectName("switch_birthday")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.switch_birthday.setFont(font)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(250, 430, 30, 21))
        self.label_12.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(450, 220, 321, 321))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(120, 430, 31, 21))
        self.label_10.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.change_mode = QtWidgets.QComboBox(self.centralwidget)
        self.change_mode.setGeometry(QtCore.QRect(120, 30, 291, 22))
        self.change_mode.setObjectName("change_mode")
        self.change_mode.addItem("")
        self.change_mode.addItem("")
        self.change_mode.addItem("")
        self.input_target2_years = QtWidgets.QLineEdit(self.centralwidget)
        self.input_target2_years.setGeometry(QtCore.QRect(150, 430, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_target2_years.setFont(font)
        self.input_target2_years.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_target2_years.setObjectName("input_target2_years")
        self.input_target1_years = QtWidgets.QLineEdit(self.centralwidget)
        self.input_target1_years.setGeometry(QtCore.QRect(150, 370, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_target1_years.setFont(font)
        self.input_target1_years.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_target1_years.setObjectName("input_target1_years")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 71, 31))
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 370, 31, 21))
        self.label_5.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 330, 71, 21))
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 260, 71, 31))
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 370, 30, 21))
        self.label_6.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.input_target1_months = QtWidgets.QLineEdit(self.centralwidget)
        self.input_target1_months.setGeometry(QtCore.QRect(210, 370, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_target1_months.setFont(font)
        self.input_target1_months.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_target1_months.setObjectName("input_target1_months")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 370, 30, 21))
        self.label_7.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setIndent(-1)
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 71, 21))
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_Clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Clear.setGeometry(QtCore.QRect(250, 490, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Clear.setFont(font)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.pushButton_Go = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Go.setGeometry(QtCore.QRect(90, 490, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Go.setFont(font)
        self.pushButton_Go.setObjectName("pushButton_Go")
        self.input_research_date = QtWidgets.QDateEdit(self.centralwidget)
        self.input_research_date.setGeometry(QtCore.QRect(120, 200, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_research_date.setFont(font)
        self.input_research_date.setObjectName("input_research_date")
        self.switch_research_date = QtWidgets.QRadioButton(self.centralwidget)
        self.switch_research_date.setGeometry(QtCore.QRect(280, 200, 141, 31))
        self.switch_research_date.setObjectName("switch_research_date")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.switch_research_date.setFont(font)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(320, 430, 30, 21))
        self.label_9.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setIndent(-1)
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 370, 31, 21))
        self.label_8.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 430, 31, 21))
        self.label_11.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.input_target2_months = QtWidgets.QLineEdit(self.centralwidget)
        self.input_target2_months.setGeometry(QtCore.QRect(210, 430, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_target2_months.setFont(font)
        self.input_target2_months.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.input_target2_months.setObjectName("input_target2_months")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(40, 70, 361, 21))
        self.label_14.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(40, 100, 381, 21))
        self.label_15.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(40, 130, 391, 21))
        self.label_16.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.switch_target_age = QtWidgets.QComboBox(self.centralwidget)
        self.switch_target_age.setGeometry(QtCore.QRect(120, 330, 69, 22))
        self.switch_target_age.setObjectName("switch_target_age")
        self.switch_target_age.addItem("")
        self.switch_target_age.addItem("")
        self.switch_target_range = QtWidgets.QComboBox(self.centralwidget)
        self.switch_target_range.setGeometry(QtCore.QRect(200, 330, 69, 22))
        self.switch_target_range.setObjectName("switch_target_range")
        self.switch_target_range.addItem("")
        self.switch_target_range.addItem("")
        AgeInDays.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AgeInDays)
        self.statusbar.setObjectName("statusbar")
        AgeInDays.setStatusBar(self.statusbar)
        self.label_2.setBuddy(self.input_research_date)
        self.label.setBuddy(self.input_birthday)
        self.label_4.setBuddy(self.change_mode)

        self.retranslateUi(AgeInDays)
        QtCore.QMetaObject.connectSlotsByName(AgeInDays)

    def retranslateUi(self, AgeInDays):
        _translate = QtCore.QCoreApplication.translate
        AgeInDays.setWindowTitle(_translate("AgeInDays", "MainWindow"))
        self.label_13.setText(_translate("AgeInDays", "～"))
        self.input_target1_days.setText(_translate("AgeInDays", "0"))
        self.input_target2_days.setText(_translate("AgeInDays", "0"))
        self.label_12.setText(_translate("AgeInDays", "ヶ月"))
        self.label_10.setText(_translate("AgeInDays", "２．"))
        self.change_mode.setItemText(0, _translate("AgeInDays", "1 - 年齢モード"))
        self.change_mode.setItemText(1, _translate("AgeInDays", "2 - アポ取りモード"))
        self.change_mode.setItemText(2, _translate("AgeInDays", "3 - 調査日決定モード"))
        self.input_target2_years.setText(_translate("AgeInDays", "1"))
        self.input_target1_years.setText(_translate("AgeInDays", "1"))
        self.label_2.setText(_translate("AgeInDays", "調査日"))
        self.label_5.setText(_translate("AgeInDays", "歳"))
        self.label_3.setText(_translate("AgeInDays", "対象年齢"))
        self.label.setText(_translate("AgeInDays", "誕生日"))
        self.label_6.setText(_translate("AgeInDays", "ヶ月"))
        self.input_target1_months.setText(_translate("AgeInDays", "0"))
        self.label_7.setText(_translate("AgeInDays", "日"))
        self.label_4.setText(_translate("AgeInDays", "計算モード"))
        self.pushButton_Clear.setText(_translate("AgeInDays", "Clear"))
        self.pushButton_Go.setText(_translate("AgeInDays", "Go"))
        self.label_9.setText(_translate("AgeInDays", "日"))
        self.label_8.setText(_translate("AgeInDays", "１．"))
        self.label_11.setText(_translate("AgeInDays", "歳"))
        self.input_target2_months.setText(_translate("AgeInDays", "0"))
        self.label_14.setText(_translate("AgeInDays", "１．　年齢モード ： 調査日と誕生日から年齢・月齢・日齢を算出"))
        self.label_15.setText(_translate("AgeInDays", "２．　アポ取りモード ： 対象年齢と調査日から対象範囲に入る誕生日を算出"))
        self.label_16.setText(_translate("AgeInDays", "３．　調査日決定モード ： 対象年齢と対象の誕生日から調査可能な期間を算出"))
        self.switch_target_age.setItemText(0, _translate("AgeInDays", "年齢"))
        self.switch_target_age.setItemText(1, _translate("AgeInDays", "月齢"))
        self.switch_target_range.setItemText(0, _translate("AgeInDays", "範囲"))
        self.switch_target_range.setItemText(1, _translate("AgeInDays", "固定"))
        self.switch_research_date.setText(_translate("AgeInDays", "カレンダー入力"))
        self.switch_birthday.setText(_translate("AgeInDays", "カレンダー入力"))

